messages:
  prefix: "&8[&aArisShop&8] &r"
  buy-success:
    text: "&aBạn đã mua thành công %amount%x %item%!"
    chat: true
    actionbar: true
  full-inventory:
    text: "&cTúi đồ của bạn đã đầy, không thể mua thêm!"
    chat: true
    actionbar: true
  insufficient-funds:
    text: "&cBạn không có đủ tiền!"
    chat: true
    actionbar: false
  insufficient-shards:
    text: "&cBạn không có đủ Shards!"
    chat: true
    actionbar: false
  reload:
    text: "&aĐã tải lại cấu hình!"
    chat: true
    actionbar: false

amount-format:
  k: "K"
  m: "M"
  b: "B"
  t: "T"

sounds:
  menu-open: "BLOCK_CHEST_OPEN"
  button-click: "UI_BUTTON_CLICK"
  cancel-click: "BLOCK_WOODEN_TRAPDOOR_CLOSE"
  purchase-success: "ENTITY_PLAYER_LEVELUP"
  purchase-fail: "ENTITY_VILLAGER_NO"

currencies:
  shards:
    balance-placeholder: "%arisshards_balance%"
    take-command: "shards take %player% %price%"

main-menu:
  title: "&8sʜᴏᴘ"
  rows: 3
  categories:
    end:
      displayname: "&#0bf592ᴇɴᴅ"
      material: END_STONE
      slot: 11
      lore:
        - "&fNhấn để mở cửa hàng End"
    nether:
      displayname: "&#0bf592ɴᴇᴛʜᴇʀ"
      material: MAGMA_BLOCK
      slot: 12
      lore:
        - "&fNhấn để mở cửa hàng Nether"
    gear:
      displayname: "&#0bf592ɢᴇᴀʀ"
      material: TOTEM_OF_UNDYING
      slot: 13
      lore:
        - "&fNhấn để mở cửa hàng Trang bị"
    food:
      displayname: "&#0bf592ꜰᴏᴏᴅ"
      material: COOKED_BEEF
      slot: 14
      lore:
        - "&fNhấn để mở cửa hàng Đồ ăn"
    shards:
      displayname: "&#0bf592sʜᴀʀᴅs"
      material: AMETHYST_SHARD
      slot: 15
      lore:
        - "&fNhấn để mở cửa hàng Shards"

gui:
  back-button:
    displayname: "&c« Quay lại Menu chính"
    material: BARRIER
    slot: 22
  quantity-selector:
    title: "&8ᴄᴏɴғɪʀᴍ ᴘᴜʀᴄʜᴀsᴇ"
    rows: 3
    cancel:
      name: "&#e00202ᴄᴀɴᴄᴇʟ"
      slot: 21
      material: RED_STAINED_GLASS_PANE
    confirm:
      name: "&#02de4fᴄᴏɴғɪʀᴍ"
      slot: 23
      material: LIME_STAINED_GLASS_PANE
    add1:
      name: "&a+1"
      slot: 15
      material: LIME_STAINED_GLASS_PANE
    add10:
      name: "&a+10"
      slot: 16
      material: LIME_STAINED_GLASS_PANE
    set64:
      name: "&aĐặt 64"
      slot: 17
      material: LIME_STAINED_GLASS_PANE
    remove1:
      name: "&c-1"
      slot: 11
      material: RED_STAINED_GLASS_PANE
    remove10:
      name: "&c-10"
      slot: 10
      material: RED_STAINED_GLASS_PANE
    remove64:
      name: "&cĐặt 1"
      slot: 9
      material: RED_STAINED_GLASS_PANE
    item-preview:
      slot: 13
      lore:
        - "&fGiá mỗi món: &#0bf52b%price%"
        - "&fSố lượng: &e%amount%x"
        - ""
        - "&fTổng cộng: &#0bf52b%total_price%"
