name: ArisShop
version: 1.1
main: me.aris.arishop.ArisShop
api-version: 1.20
author: VennLMAO
description: He thong cua hang nang cao cho Aris Network
folia-supported: true
commands:
  shop:
    description: Mo menu cua hang chinh
    aliases: [arishop, cuahang]
permissions:
  arishop.use:
    description: Cho phep nguoi dung mo shop
    default: true
