name: ArisShop
version: 1.0
main: me.aris.arisshop.ArisShop
api-version: '1.20'
author: VennLMAO
description: Hệ thống cửa hàng độc quyền cho Aris Network
depend: [Vault]

commands:
  arisshop:
    description: Lệnh chính để mở cửa hàng
    aliases: [shop, aris, cuahang]
    permission: arisshop.use

permissions:
  arisshop.use:
    description: Cho phép người chơi sử dụng cửa hàng
    default: true
  arisshop.admin:
    description: Quyền quản trị viên để tải lại plugin
    default: op
